config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'dashboard/index'
  end

  resources :categories do
    member do
      get 'notes'
    end
  end

  root to: 'dashboard#index'
  resources :sales_items

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sales_items
end

app/models/sales_item.rb
class SalesItem < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  def notes
    category = Category.find(params[:id])
    render json: category
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name,:notes)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/sales_items_controller.rb
class SalesItemsController < ApplicationController
  before_action :set_sales_item, only: [:show, :edit, :update, :destroy]

  # GET /sales_items
  # GET /sales_items.json
  def index
    @sales_items = SalesItem.all
  end

  # GET /sales_items/1
  # GET /sales_items/1.json
  def show
  end

  # GET /sales_items/new
  def new
    @sales_item = SalesItem.new
  end

  # GET /sales_items/1/edit
  def edit
  end

  # POST /sales_items
  # POST /sales_items.json
  def create
    @sales_item = SalesItem.new(sales_item_params)

    respond_to do |format|
      if @sales_item.save
        format.html { redirect_to @sales_item, notice: 'Sales item was successfully created.' }
        format.json { render :show, status: :created, location: @sales_item }
      else
        format.html { render :new }
        format.json { render json: @sales_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales_items/1
  # PATCH/PUT /sales_items/1.json
  def update
    respond_to do |format|
      if @sales_item.update(sales_item_params)
        format.html { redirect_to @sales_item, notice: 'Sales item was successfully updated.' }
        format.json { render :show, status: :ok, location: @sales_item }
      else
        format.html { render :edit }
        format.json { render json: @sales_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_items/1
  # DELETE /sales_items/1.json
  def destroy
    @sales_item.destroy
    respond_to do |format|
      format.html { redirect_to sales_items_url, notice: 'Sales item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_item
      @sales_item = SalesItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sales_item_params
      params.require(:sales_item).permit(:name, :category_id, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sales_items_helper.rb
module SalesItemsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Notes</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.notes %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a href="/categories/new">New Category</a>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Notes</strong>
  <%= @category.notes %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/dashboard/index.html.erb
<h1 class="centered fancy">Dashboard</h1>

<div id="welcome">
  <h2 id="welcome-message">Welcome to the Inventory System</h2>

  <p>
    You have <%= SalesItem.count %> items defined in the system.
  </p>

  <p>The <span id="average" class="bold-blue">average</span> price of a sales item is <%= number_to_currency(SalesItem.average(:price)) %>.</p>

</div>

<p id="description">The average is the sum divided by the count.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CIS 4339 Homework - JQuery and CSS</title>
    <link data-turbolinks-track="true" href="/assets/application.css" media="all" rel="stylesheet" />
    <script data-turbolinks-track="true" src="/assets/application.js."></script>
    <meta content="authenticity_token" name="csrf-param" />
    <meta content="5s0B89wIbsPNlrOeEJOV83S7iQY97nn4RrHMpBSQuFs=" name="csrf-token" />
  </head>
  <body>
    <div id="header">
      <h1>Inventory Manager</h1>
      <a href="/">Dashboard</a>
      <a href="/sales_items">Sales Items</a>
      <a href="/categories">Categories</a>
    </div>
    <%= yield %>
  </body>
</html>

app/views/sales_items/_form.html.erb
<%= form_for(@sales_item) do |f| %>
  <% if @sales_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sales_item.errors.count, "error") %> prohibited this sales_item from being saved:</h2>

      <ul>
      <% @sales_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all,:id,:name %>
    <br/>

    <p>Notes on Category: <span id="notes"></span></p>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
    <p id="price_warning"></p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales_items/edit.html.erb
<h1>Editing Sales Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @sales_item %> |
<%= link_to 'Back', sales_items_path %>

app/views/sales_items/index.html.erb
<h1>Sales Items</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Price</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>

  <tbody>
    <% @sales_items.each do |sales_item| %>
      <tr>
        <td><%= sales_item.name %></td>
        <td><%= sales_item.category.name %></td>
        <td><%= number_to_currency(sales_item.price, unit: "$") %></td>
        <td><%= link_to 'Show', sales_item %></td>
        <td><%= link_to 'Edit', edit_sales_item_path(sales_item) %></td>
        <td><%= link_to 'Destroy', sales_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
    <% end %>
  </tbody>
</table>

<br>

<a href="/sales_items/new">New Sales item</a>

app/views/sales_items/new.html.erb
<h1>New Sales Item</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_items_path %>

app/views/sales_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sales_item.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @sales_item.category.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@sales_item.price, unit: "$") %>
</p>

<%= link_to 'Edit', edit_sales_item_path(@sales_item) %> |
<%= link_to 'Back', sales_items_path %>